{
  "data": [
    {
      "name": "Jamie Lanniester",
      "gender": "Male",
      "streetaddress": "122 Spring River Drive",
      "city": "Redmond",
      "state": "Washington",
      "zipcode": "98053",
      "designation": "Data Engineer",
      "office": "Seattle",
      "phonenumber": "111-222-2222",
      "extension": "8422",
      "joining_date": "2011/07/25",
      "salary": "$150,000"
    },
    {
      "name": "Brianne Tar",
      "gender": "Female",
      "streetaddress": "66 Spring Valley Drive",
      "city": "Buffalo",
      "state": "New York",
      "zipcode": "14201",
      "designation": "Accountant",
      "office": "New York city",
      "phonenumber": "345-363-3333",
      "extension": "4804",
      "joining_date": "2012/12/02",
      "salary": "$120,000"
    },
    {
      "name": "Arya Stark",
      "gender": "Female",
      "streetaddress": "298 Forest Lane",
      "city": "San Francisco",
      "state": "California",
      "zipcode": "94016",
      "designation": "Junior Technical Author",
      "office": "San Francisco",
      "phonenumber": "777-888-0000",
      "extension": "1562",
      "joining_date": "2009/01/12",
      "salary": "$86,000"
    },
    {
      "name": "Cercie Jobs",
      "gender": "Female",
      "streetaddress": "1234 Main Street",
      "city": "Kirkland",
      "state": "Washington",
      "zipcode": "98033",
      "designation": "Software Developer",
      "office": "Seattle",
      "phonenumber": "908-098-0989",
      "extension": "5407",
      "joining_date": "2008/11/28",
      "salary": "$162,700"
    },
    {
      "name": "Julius Caesor",
      "gender": "Male",
      "streetaddress": "293 River Lane",
      "city": "Orlando",
      "state": "Florida",
      "zipcode": "32789",
      "designation": "Pre-Sales Support",
      "office": "Florida",
      "phonenumber": "333-444-6754",
      "extension": "8330",
      "joining_date": "2011/12/12",
      "salary": "$106,450"
    },
    {
      "name": "Molly Anderson",
      "gender": "Female",
      "streetaddress": "1000 Main Street",
      "city": "Miami",
      "state": "Florida",
      "zipcode": "33101",
      "designation": "Regional Director",
      "office": "Florida".
      "phonenumber": "222-111-1110",
      "extension": "8330",
      "joining_date": "2008/11/13",
      "salary": "$183,000"
    },
    {
      "name": "Cedric Kelly",
      "gender": "Male",
      "streetaddress": "300 Gillet Lane",
      "city": "Bellevue",
      "state": "Washington",
      "zipcode": "98007",
      "designation": "Senior Javascript Developer",
      "office": "Seattle",
      "phonenumber": "777-444-7890",
      "extension": "6224",
      "joining_date": "2012/03/29",
       "salary": "$433,060"
    },
    {
      "name": "Jennifer Aniston",
      "gender": "Female",
      "streetaddress": "45 North West Lane",
      "city": "San Francisco",
      "state": "California",
      "zipcode": "94103",
      "designation": "Senior Marketing Designer",
      "office": "San Francisco",
      "phonenumber": "378-098-0987",
      "extension": "3597",
      "joining_date": "2012/12/18",
      "salary": "$313,500"
    },
    {
      "name": "Ross Hurst",
      "gender": "Male",
      "streetaddress": "12 Seneca Lane",
      "city": "Newark",
      "state": "New Jersey",
      "zipcode": "07101",
      "designation": "Javascript Developer",
      "office": "Newark",
      "phonenumber": "109-091-1023",
      "extension": "2360",
      "joining_date": "2009/09/15",
      "salary": "$205,500"
    },
    {
      "name": "Dai Rios",
      "gender": "Male",
      "streetaddress": "400 Drivers Lane",
      "city": "Buffallo",
      "state": "New York",
      "zipcode": "14206",
      "designation": "Personnel Lead",
      "office": "New York City",
      "phonenumber": "202-828-7272",
      "extension": "2290",
      "joining_date": "2012/09/26",
      "salary": "$217,500"
    },
    {
      "name": "Nancy Jain",
      "gender": "Female",
      "streetaddress": "60 Belred Lane",
      "city": "Bellevue",
      "state": "Washington",
      "zipcode": "98009",
      "designation": "Sales Assistant",
      "office": "Seattle",
      "phonenumber": "131-141-1515",
      "extension": "9608",
      "joining_date": "2012/08/06",
      "salary": "$137,500"
    },
    {
      "name": "Prateek Jain",
      "gender": "Male",
      "streetaddress": "70 Cross Roads",
      "city": "San Francisco",
      "state": "California",
      "zipcode": "94114",
      "designation": "Integration Specialist",
      "office": "San Francisco",
      "phonenumber": "676-575-5765",
      "extension": "6200",
      "joining_date": "2010/10/14",
      "salary": "$327,900"
    },
    {
      "name": "Sonya Singh",
      "gender": "Female",
      "streetaddress": "600 China Lane",
      "city": "Bothell",
      "state": "Washington",
      "zipcode": "98034",
      "designation": "Software Engineer",
      "office": "Seattle",
      "phonenumber": "278-786-7648",
      "extension": "1667",
      "joining_date": "2008/12/13",
      "salary": "$103,600"
    },
    {
      "name": "Jena Gaines",
      "gender": "Female",
      "streetaddress": "700 Mells Lane",
      "city": "Bothell",
      "state": "Washington",
      "zipcode": "98021",
      "designation": "Office Manager",
      "office": "Seattle",
      "phonenumber": "292-202-2626",
      "extension": "3814",
      "joining_date": "2008/12/19",
      "salary": "$90,560"
    },
    {
      "name": "Quinn Flynn",
      "gender": "Male",
      "streetaddress": "3445 Cheyenne Road",
      "city": "Kirkland",
      "state": "Washington",
      "zipcode": "98033",
      "designation": "Support Lead",
      "office": "Seattle",
      "phonenumber": "242-222-2222",
      "extension": "9497",
      "joining_date": "2013/03/03",
      "salary": "$342,000"
    }
  ]
}